### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wildlips07**

### CODE REVIEW

**Review by Duongtaocode — COMMENTED** [review]
https://www.facebook.com/profile.php?id=61558924804722&mibextid=ZbWKwL

**Review by Duongtaocode — COMMENTED** [review]
https://mbasic.facebook.com/share/p/5dAnGj58t24YGsdE/?mibextid=oFDknk

**Comment by Duongtaocode** [comment]
OK

**Review by Duongtaocode — APPROVED** [review]

**Review by Duongtaocode — APPROVED** [review]
https://mbasic.facebook.com/share/p/5dAnGj58t24YGsdE/?mibextid=oFDknk

**Review by Duongtaocode — APPROVED** [review]
100

**Comment by warifp** [comment]
Not exactly.

**Pull request closed without merging**
